---
- name: Create MongoDB Group
  group:
    name: "{{mongodb_os_user['name']}}"
    state: present

- name: Create MongoDB OS User
  user:
    name: "{{mongodb_os_user['name']}}"
    uid: "{{mongodb_os_user['uid']}}"
    shell: "{{mongodb_os_user['shell']}}"
    home: "{{mongodb_os_user['home']}}"
    group: "{{mongodb_os_user['name']}}"
    append: true

- name: Install Python Tools
  yum: name={{ item }} state=latest
  with_items:
    - libselinux-python
    - python-devel
    - python-pip
    - python-urllib3

#Python Versions bellow 2.7.9 have issues with SSL Certificates
#We gonna install pymongo directly, case this is true for the dbserver
- name: Get Python Version
  shell: python --version 2>&1 | grep -Po '(?<=Python )[^;]+'
  register: python_version
  
- name: Install PyMongo from PIP
  pip:
    name: pymongo
    state: latest
  when:  python_version.stdout_lines[0] is version('2.7.8', operator='gt', strict=True)

- include: setup-pymongo26.yml
  when: python_version.stdout_lines[0] is version('2.7.9', operator='lt', strict=True)
